#!/usr/bin/env bash
# generated by submit_sco_fullbatch.py -- records exactly what this job ran
set -u
cd /data/sunruoyu/wangsenmiao/Data-Imbalance-Hessian/hessian-spectrum-xinlurepo-senmiao/toy_models || exit 1
export PATH="/data/sunruoyu/wangsenmiao/miniconda3/envs/pc/bin:$PATH"
mkdir -p logs/fullbatch-gd-vs-adam-002 || exit 1
echo "[fullbatch] host=$(hostname) cwd=$(pwd)"
/data/sunruoyu/wangsenmiao/miniconda3/envs/pc/bin/python -c "import torch; print('[fullbatch] torch', torch.__version__, 'cuda_available', torch.cuda.is_available(), 'device_count', torch.cuda.device_count())"

# --- GPU 0: fullbatch-mse0-shuffled-gd
CUDA_VISIBLE_DEVICES=0 /data/sunruoyu/wangsenmiao/miniconda3/envs/pc/bin/python -u train_fullbatch.py fullbatch-mse0-shuffled-gd > logs/fullbatch-gd-vs-adam-002/gpu0-fullbatch-mse0-shuffled-gd.log 2>&1 &
PID0=$!
echo "[fullbatch] GPU 0 pid $PID0: fullbatch-mse0-shuffled-gd"
# --- GPU 1: fullbatch-mse0-shuffled-adam
CUDA_VISIBLE_DEVICES=1 /data/sunruoyu/wangsenmiao/miniconda3/envs/pc/bin/python -u train_fullbatch.py fullbatch-mse0-shuffled-adam > logs/fullbatch-gd-vs-adam-002/gpu1-fullbatch-mse0-shuffled-adam.log 2>&1 &
PID1=$!
echo "[fullbatch] GPU 1 pid $PID1: fullbatch-mse0-shuffled-adam"

sleep 5
tail -n +1 -f logs/fullbatch-gd-vs-adam-002/gpu0-fullbatch-mse0-shuffled-gd.log logs/fullbatch-gd-vs-adam-002/gpu1-fullbatch-mse0-shuffled-adam.log &
TAILPID=$!

rc=0
if wait $PID0; then
  echo "[fullbatch] GPU 0 OK: fullbatch-mse0-shuffled-gd"
else
  echo "[fullbatch] GPU 0 FAILED: fullbatch-mse0-shuffled-gd"; rc=1
fi
if wait $PID1; then
  echo "[fullbatch] GPU 1 OK: fullbatch-mse0-shuffled-adam"
else
  echo "[fullbatch] GPU 1 FAILED: fullbatch-mse0-shuffled-adam"; rc=1
fi

sleep 2
kill $TAILPID 2>/dev/null
echo "[fullbatch] all runs finished, rc=$rc"
exit $rc
